# Coolify Deployment Configuration
# https://coolify.io/docs/knowledge-base/docker/compose

services:
  # ==========================================
  # API Service (Express.js backend)
  # ==========================================
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    expose:
      - "3000"

  # ==========================================
  # Storefront (Next.js)
  # ==========================================
  storefront:
    build:
      context: .
      dockerfile: apps/storefront/Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - API_URL=http://api:3000
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    expose:
      - "3000"

  # ==========================================
  # Admin Panel (Vite + React)
  # ==========================================
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    expose:
      - "80"

  # ==========================================
  # Blog (Remix)
  # ==========================================
  blog:
    build:
      context: .
      dockerfile: apps/blog/Dockerfile
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    expose:
      - "3000"
